# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_activate', models.IntegerField()),
                ('status_lock', models.IntegerField()),
                ('status_real_name', models.IntegerField()),
                ('status_delete', models.IntegerField()),
                ('time_activate', models.DateTimeField(blank=True, null=True)),
                ('time_lock', models.DateTimeField(blank=True, null=True)),
                ('time_real_name', models.DateTimeField(blank=True, null=True)),
                ('time_delete', models.DateTimeField(blank=True, null=True)),
                ('time_create', models.DateTimeField()),
                ('time_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
    ]
